apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-alpine-deployment
  labels:
    label: my-alpine
spec:
  selector:
    matchLabels:
      app: my-alpine
  replicas: 1
  template:
    metadata:
      labels:
        app: my-alpine
    spec:
      containers:
        - name: my-alpine
          image:  alpine
          command: 
          - cat
          tty: true

